// Use the production server bundle generated by `react-router build`.
// This avoids Vercel trying to compile raw TypeScript server sources at runtime.
// @ts-ignore -- build/server/index.js is generated at build time and has no type declarations
export { default } from '../build/server/index.js';
